### ISSUE TITLE
Working on a spanish version of this guide

### ISSUE THREAD

**Issue by gabelula** [ireapps/first-news-app#32]
I'm working on a version in spanish of this guide. 
https://github.com/gabelula/first-news-app
It is not finished yet but I'm also changing the dataset for the one about fires in Spain that the app http://espanaenllamas.es/ used. 
I also used this guide to make a presentation about how to make a news app at Jornadas de Periodismo de Datos in Spain.

Jornadas: http://periodismodatos.okfn.es
Presentation: http://gabelula.github.io/first-news-app-presentacion-barna/#/

The spanish version of the guide is http://first-news-app-spanish.readthedocs.org/es/latest/

**Comment by palewire** [comment]
I'm working on lightly revising this guide for the upcoming 2015 version of the NICAR conference. Do you have any updates on your end?

**Comment by gabelula** [comment]
Nop. I used a different data set for the spanish version. But the same tools and platform for the news app.

**Comment by palewire** [comment]
K. If you're interested, take a look at the latest English version. I reworked how the CSV is opened to make it more literate for a beginner (i.e. no list comprehensions).
